name: C++ CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      env:
        dependency_packages: build-essential g++-5
      run: sudo apt-get update && sudo apt-get -y install ${dependency_packages}

    - name: Build
      run: |
        mkdir -p build && cd build
        cmake ..
        cmake --build . --config Release -- -j4

    - name: Test
      run: ctest -C Release -V
